# =============================================================================
# modules/data — RDS MySQL + Secrets Manager        (GROUP-OWNED: Joyce, PR #1)
#
# Create a managed MySQL instance and publish its credentials to Secrets Manager
# using the shared envelope. NO plaintext secret in git, in the image, or in any
# output that gets logged.
#
# Inputs  -> variables.tf
# Outputs -> outputs.tf  (db_endpoint, db_port, secret_arn, secret_name)
# =============================================================================

# -----------------------------------------------------------------------------
# DB master password. Generated by Terraform so it never appears in git.
# special = false keeps it out of trouble with the Secrets Manager JSON envelope
# and MySQL connection strings. It still lands in state in cleartext — there is
# no random_password arrangement that avoids that, so state is a credential store
# (see FIDELITY.md / C3): encrypted bucket, versioned, non-public, gitignored.
# -----------------------------------------------------------------------------
resource "random_password" "db" {
  length  = 24
  special = false
}

# -----------------------------------------------------------------------------
# Managed MySQL instance.
# Right-sizing rationale lives in variable defaults + the root README.
# -----------------------------------------------------------------------------
resource "aws_db_instance" "mysql" {
  identifier     = "${var.project_name}-mysql"
  engine         = "mysql"
  engine_version = var.engine_version
  instance_class = var.instance_class

  allocated_storage = var.allocated_storage
  storage_type      = "gp3"

  db_name  = var.db_name
  username = var.db_username
  password = random_password.db.result

  # Lab trade-offs — each is documented in FIDELITY.md as declared-vs-enforced
  # on LocalStack:
  multi_az            = false # single-AZ: accepting no automatic failover for a lab
  publicly_accessible = false # not reachable from outside the VPC (trivy: AVD-AWS-0180)
  storage_encrypted   = true  # LocalStack echoes this back but applies no encryption

  # Lab lifecycle: make destroy fast and unattended.
  skip_final_snapshot = true
  deletion_protection = false # false so `make destroy` can tear the stack down
  apply_immediately   = true
}

# -----------------------------------------------------------------------------
# Secrets Manager: publish the credential envelope. user-data / the app receive
# the ARN and resolve the value at runtime via GetSecretValue.
# -----------------------------------------------------------------------------
resource "aws_secretsmanager_secret" "db" {
  name        = var.secret_name
  description = "MySQL credentials for ${var.project_name} (Regional Health capacity lab)."
}

resource "aws_secretsmanager_secret_version" "db" {
  secret_id = aws_secretsmanager_secret.db.id

  # Envelope keys EXACTLY: engine, username, password, host, port, dbname.
  # host/port come from the live instance attributes.
  secret_string = jsonencode({
    engine   = "mysql"
    username = var.db_username
    password = random_password.db.result
    host     = aws_db_instance.mysql.address
    port     = aws_db_instance.mysql.port
    dbname   = var.db_name
  })
}
